# Plugins
gems:
- jekyll-sitemap
safe: true

# Build Settings
permalink: pretty
exclude: ['/bin/', 'README.md', 'LICENSE.txt', 'CNAME', 'package.json', '/node_modules/', 'gulpfile.js', '.jshintrc', 'web-codemotion.sublime-project', 'web-codemotion.sublime-workspace', '/.git/', '.gitignore']

# Site Settings

# i18n
en:
  title: "Codemotion Spain - For the communities, by the communities"
  description: "Codemotion is the event that gets all the IT communities in Spain together for two days."
  mainTitle: "Codemotion Spain"
  mainSubtitle: "Nov 27-28 2015"
  SendYourTalk: "Send your proposal"
  aboutTitle: "Be an agent of chaos"
  aboutDesc: "<p class='lead'>There must be a creation process. There must be change.</p><p>We, the IT crowd, recognize the need to reinvent our ways every year, learning new formulas to do old things. We don't relax believing that what was best practice last year will remain unchanged, unaffected by time. That's how Cobol was born. We don't do that.</p><p>We are agents of change. We recognize the need to destroy in order to build. We go, and get together, and learn. Then we get back to our places of work, and break things.</p><p>That's what we do.</p>"
  aboutBlock:
    - title: "+1,900 Attendees"
      text: "With more than 1,900 software enthusiasts, Codemotion is the biggest IT event in Spain."
    - title: "+30 Communities"
      text: "Codemotion is possible because of all the communities that are behind, contributing with their support and curiosity."
    - title: "+130 Talks & Workshops"
      text: "Quality is important to us. That's why we go through all flavors of pain to filter the best talks and workshops. "
  locationBlockTitle: "Location"
  viewOnGoogleMaps: "View on Google Maps"
  parkingAvailability: "The parking has a limited capacity, and there will be many of us. We recommend to take the public transport, which is surprisingly easy:"
  checkGPS: '<b>THIS IS NOT THE SAME AS "CAMPUS DE MONCLOA".</b> Please double-check your GPS instructions.'
  metroLigero: "L3 (direction Puerta de Boadilla, drop at MontePríncipe)"
  CallForPapers: 'Call for papers'
  CallForPapersDesc: "Do you want to share what makes you excited about technology? Enter our Call for Papers <b>open until June 30</b> and post your talk or workshop."
  developedBy: '<span>Developed with</span><span class="icon-heart"></span><span>by</span>'
  SponsorsTitle: 'Become a sponsor'
  SponsorsDesc: 'Codemotion is the biggest tech conference in Spain and one of the most important in Europe, with a network of more than 30K developers. Take part as a sponsor in the event open to all languages, platforms and technologies.'
  CommunitiesTitle: 'Communities'
  CommunitiesDesc: 'This event would not be possible without our communities. They provide with the talks and content that make all this possible.'
  AskForInvitation: 'Ask for an invitation'
  ContactUs: 'Contact us'

es:
  title: "Codemotion Spain - For the communities, by the communities"
  description: "Codemotion es el evento que junta a todas las comunidades de desarrolladores IT de España durante dos días."
  mainTitle: "Codemotion Spain"
  mainSubtitle: "Nov 27-28 2015"
  SendYourTalk: "Envíanos tu charla"
  aboutTitle: "Sé un agente del caos"
  aboutDesc: "<p class='lead'>Tiene que haber un proceso creativo. Tiene que haber cambio.</p><p>Nosotros, la comunidad de técnicos del software, reconocemos la necesidad de reinventarnos cada año, aprendiendo fórmulas nuevas para hacer las cosas de siempre. No nos relajamos pensando que lo que era buena práctica el año pasado seguirá sin cambios hoy, sin verse afectada por el paso del tiempo. Así es como nació Cobol. Nosotros no hacemos eso.</p><p>Nosotros somos agentes del cambio. Reconocemos la necesidad de destruir para construir después. Vamos, nos juntamos, y aprendemos juntos. Después volvemos a nuestros lugares de trabajo, y rompemos cosas.</p><p>Esto es lo que hacemos.</p>"
  aboutBlock:
    - title: "+1,900 Asistentes"
      text: "Con más de 1,900 entusiastas del código, Codemotion se ha convertido en el evento de IT más grande de España."
    - title: "+30 Comunidades"
      text: "Codemotion es posible gracias a todas las comunidades que colaboran con su apoyo y curiosidad."
    - title: "+130 Charlas & Workshops"
      text: "La calidad es importante para nosotros. Por eso pasamos por un arco iris de dolor para seleccionar las mejores charlas y workshops. "
  locationBlockTitle: "Dónde"
  viewOnGoogleMaps: "Ver en Google Maps"
  parkingAvailability: "El parking tiene capacidad limitada, y seremos bastantes. Recomendamos usar el transporte público, que es sorprendentemente sencillo:"
  checkGPS: '<b>ESTO NO ES LO MISMO QUE "CAMPUS DE MONCLOA".</b> Por favor, comprueba las instrucciones de tu GPS.'
  metroLigero: "L3 (dirección Puerta de Boadilla, bajarse en MontePríncipe)"
  CallForPapers: 'Call for papers'
  CallForPapersDesc: "Tienes una tecnología que te apasiona y que quieres compartir? Participa en nuestro Call for Papers <b>abierto hasta el 30 de Junio</b> en las categorías de charla o workshop."
  developedBy: '<span>Desarrollado con</span><span class="icon-heart"></span><span>por</span>'
  SponsorsTitle: 'Conviértete en patrocinador'
  SponsorsDesc: 'Codemotion es el mayor evento en España y uno de los más importantes de Europa, con una red de más de 30K desarrolladores. Toma parte como patrocinador en el evento abierto a todos los lenguajes, plataformas y tecnologías.'
  CommunitiesTitle: 'Nuestras comunidades'
  CommunitiesDesc: 'Este evento no sería posible sin la participación de nuestras comunidades. Ellas son las que producen el contenido que da sentido a todo esto.'
  AskForInvitation: 'Solicita incluir tu comunidad'
  ContactUs: 'Contáctanos'

email: "info@codemotion.es"
baseurl: ""
url: "codemotion.es"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""

# Head
twitterAccount: "@codemotion_es"

# Main Block
mainImage: "codemotion.jpg"
mainButtons:
  - link: "https://www.koliseo.com/codemotion/codemotion-madrid/r4p/5685252034920448"
    i18n: "SendYourTalk"


# Location Block
universityName: "Universidad San Pablo CEU"
streetAddress: "Campus de Montepríncipe"
addressLocality: "Boadilla del monte, Madrid"
placeCoordinates: "40.399567, -3.837917,17"
mapCenterCoordinates: "40.399567, -3.839917,17"
mobileCenterMapCoordinates: "40.399567, -3.837917"