# Plugins
gems:
- jekyll-sitemap
safe: true

# Build Settings
permalink: pretty
exclude: ['/bin/', 'README.md', 'LICENSE.txt', 'CNAME', 'package.json', '/node_modules/', 'gulpfile.js', '.jshintrc', 'web-codemotion.sublime-project', 'web-codemotion.sublime-workspace', '/.git/', '.gitignore']

# Site Settings

# i18n
en:
  title: "Codemotion Spain - For the communities, by the communities"
  description: "Codemotion is the event that gets all the IT communities in Spain together for two days."
  mainTitle: "Codemotion Spain"
  mainSubtitle: "Nov 27-28 2015"
  SendYourTalk: "Send your proposal"
  aboutTitle: "Be an agent of chaos"
  aboutDesc: "<p class='lead'>There must be a creation process. There must be change.</p><p>We, the IT crowd, recognize the need to reinvent our ways every year, learning new formulas to do old things. We don't relax believing that what was best practice last year will remain unchanged, unaffected by time. That's how Cobol was born. We don't do that.</p><p>We are agents of change. We recognize the need to destroy in order to build. We go, and get together, and learn. Then we get back to our places of work, and break things.</p><p>That's what we do.</p>"
  aboutBlock:
    - title: "+1,900 Attendees"
      text: "With more than 1,900 software enthusiasts, Codemotion is the biggest IT event in Spain."
    - title: "+30 Communities"
      text: "Codemotion is possible because of all the communities that are behind, contributing with their support and curiosity."
    - title: "+130 Talks & Workshops"
      text: "Quality is important to us. That's why we go through all flavors of pain to filter the best talks and workshops. "
  locationBlockTitle: "Location"
  viewOnGoogleMaps: "View on Google Maps"
  parkingAvailability: "The parking has a limited capacity, and there will be many of us. We recommend to take the public transport, which is surprisingly easy:"
  checkGPS: '<b>THIS IS NOT THE SAME AS "CAMPUS DE MONCLOA".</b> Please double-check your GPS instructions.'
  metroLigero: "L3 (direction Puerta de Boadilla, drop at MontePríncipe)"
  CallForPapers: 'Call for papers'
  CallForPapersDesc: "Do you want to share what makes you excited about technology? Enter our Call for Papers <b>open until June 30</b> and post your talk or workshop."
  developedBy: '<span>Developed with</span><span class="icon-heart"></span><span>by</span>'
  SponsorsTitle: 'Become a sponsor'
  SponsorsDesc: 'Codemotion is the biggest tech conference in Spain and one of the most important in Europe, with a network of more than 30K developers. Take part as a sponsor in the event open to all languages, platforms and technologies.'
  CommunitiesTitle: 'Communities'
  CommunitiesDesc: 'This event would not be possible without our communities. They provide with the talks and content that make all this possible.'
  AskForInvitation: 'Ask for an invitation'
  ContactUs: 'Contact us'
  codeOfConduct: 'Code of Conduct'
  cocHeadingTitle: "Code of Conduct"
  cocHeading: "All attendees, speakers, sponsors and volunteers at our conference are required to agree with the following code of conduct. Organisers will enforce this code throughout the event. We are expecting cooperation from all participants to help ensuring a safe environment for everybody."
  cocHelpTitle: "Help"
  cocHelp: "You can find our contact details, info@codemotion.es, in all the emails we've sent. "
  cocQuickTitle: "The Quick Version"
  cocQuick: "Our conference is dedicated to providing a harassment-free conference experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, or religion (or lack thereof). We do not tolerate harassment of conference participants in any form. Sexual language and imagery is not appropriate for any conference venue, including talks, workshops, parties, Twitter and other online media. Conference participants violating these rules may be sanctioned or expelled from the conference without a refund at the discretion of the conference organisers."
  cocMainTitle: "The Less Quick Version"
  cocMain: >
           Harassment includes offensive verbal comments related to gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention.
           Participants asked to stop any harassing behavior are expected to comply immediately.
           Sponsors are also subject to the anti-harassment policy. In particular, sponsors should not use sexualised images, activities, or other material. Booth staff (including volunteers) should not use sexualised clothing/uniforms/costumes, or otherwise create a sexualised environment.
           If a participant engages in harassing behavior, the conference organisers may take any action they deem appropriate, including warning the offender or expulsion from the conference with no refund.
           If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact a member of conference staff immediately. Conference staff can be identified as they'll be wearing branded t-shirts.
           Conference staff will be happy to help participants contact hotel/venue security or local law enforcement, provide escorts, or otherwise assist those experiencing harassment to feel safe for the duration of the conference. We value your attendance.
           We expect participants to follow these rules at conference and workshop venues and conference-related social events.
           
  cocCredits: >
              Original source and credit: <a href="http://2012.jsconf.us/#/about">http://2012.jsconf.us/#/about</a> &amp; <a href="http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy">The Ada Initiative</a><br>
              Please help by translating or improving: <a href="https://github.com/leftlogic/confcodeofconduct.com">http://github.com/leftlogic/confcodeofconduct.com</a><br>
              This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/deed.en_US">Creative Commons Attribution 3.0 Unported License</a>
            

es:
  title: "Codemotion Spain - For the communities, by the communities"
  description: "Codemotion es el evento que junta a todas las comunidades de desarrolladores IT de España durante dos días."
  mainTitle: "Codemotion Spain"
  mainSubtitle: "Nov 27-28 2015"
  SendYourTalk: "Envíanos tu charla"
  aboutTitle: "Sé un agente del caos"
  aboutDesc: "<p class='lead'>Tiene que haber un proceso creativo. Tiene que haber cambio.</p><p>Nosotros, la comunidad de técnicos del software, reconocemos la necesidad de reinventarnos cada año, aprendiendo fórmulas nuevas para hacer las cosas de siempre. No nos relajamos pensando que lo que era buena práctica el año pasado seguirá sin cambios hoy, sin verse afectada por el paso del tiempo. Así es como nació Cobol. Nosotros no hacemos eso.</p><p>Nosotros somos agentes del cambio. Reconocemos la necesidad de destruir para construir después. Vamos, nos juntamos, y aprendemos juntos. Después volvemos a nuestros lugares de trabajo, y rompemos cosas.</p><p>Esto es lo que hacemos.</p>"
  aboutBlock:
    - title: "+1,900 Asistentes"
      text: "Con más de 1,900 entusiastas del código, Codemotion se ha convertido en el evento de IT más grande de España."
    - title: "+30 Comunidades"
      text: "Codemotion es posible gracias a todas las comunidades que colaboran con su apoyo y curiosidad."
    - title: "+130 Charlas & Workshops"
      text: "La calidad es importante para nosotros. Por eso trabajamos duro para seleccionar las mejores charlas y workshops. "
  locationBlockTitle: "Dónde"
  viewOnGoogleMaps: "Ver en Google Maps"
  parkingAvailability: "El parking tiene capacidad limitada, y seremos bastantes. Recomendamos usar el transporte público, que es sorprendentemente sencillo:"
  checkGPS: '<b>ESTO NO ES LO MISMO QUE "CAMPUS DE MONCLOA".</b> Por favor, comprueba las instrucciones de tu GPS.'
  metroLigero: "L3 (dirección Puerta de Boadilla, bajarse en MontePríncipe)"
  CallForPapers: 'Call for papers'
  CallForPapersDesc: "Tienes una tecnología que te apasiona y que quieres compartir? Participa en nuestro Call for Papers <b>abierto hasta el 30 de Junio</b> en las categorías de charla o workshop."
  developedBy: '<span>Desarrollado con</span><span class="icon-heart"></span><span>por</span>'
  SponsorsTitle: 'Conviértete en patrocinador'
  SponsorsDesc: 'Codemotion es el mayor evento en España y uno de los más importantes de Europa, con una red de más de 30K desarrolladores. Toma parte como patrocinador en el evento abierto a todos los lenguajes, plataformas y tecnologías.'
  CommunitiesTitle: 'Nuestras comunidades'
  CommunitiesDesc: 'Este evento no sería posible sin la participación de nuestras comunidades. Ellas son las que producen el contenido que da sentido a todo esto.'
  AskForInvitation: 'Solicita incluir tu comunidad'
  ContactUs: 'Contáctanos'
  codeOfConduct: 'Código de Conducta'
  cocHeadingTitle: "Código de Conducta"
  cocHeading: "Se requiere que todos los asistentes, ponentes, patrocinadores y voluntarios de nuestra conferencia acepten el siguiente código de conducta. Los organizadores harán cumplir este código a lo largo del evento. Esperamos la colaboración de todos los participantes para ayudar a asegurar un ambiente seguro para todos."
  cocHelpTitle: "¿Necesitas Ayuda?"
  cocHelp: "Tienes nuestros detalles de contacto, info@codemotion.es, en los correos electrónicos que hemos mandado."
  cocQuickTitle: "La Versión Rápida"
  cocQuick: "Nuestra conferencia se dedica a ofrecer una experiencia libre de abusos para todos, independientemente de su género, orientación sexual, discapacidad, apariencia física, talla, raza o religión. No toleramos abusos de los participantes de la conferencia en ninguna de sus formas. El lenguaje e imágenes sexuales no son apropiados para ninguna sala de la conferencia, incluyendo charlas, talleres, fiestas, Twitter y otros medios online. Los participantes de la conferencia que violen estas reglas pueden ser sancionados o expulsados de la misma sin reembolso a discreción de los organizadores."
  cocMainTitle: "La Versión No Tan Rápida"
  cocMain: >
           Los abusos incluyen: comentarios ofensivos relativos a género, orientación sexual, discapacidad, apariencia física, talla, raza, religión, imágenes sexuales en espacios públicos, intimidación deliberada, acoso, persecución, fotografía o grabación de abusos, interrupciones continuadas de charlas u otros eventos, contacto físico inapropiado y atención sexual no deseada.
           Se espera que los participantes instados a parar cualquier comportamiento abusivo obedezcan inmediatamente.
           Los patrocinadores también están sujetos a la política contra abusos. En particular, los patrocinadores no deberían utilizar imágenes, actividades u otro material con contenido sexual. El personal de los puestos (voluntarios incluidos) no debería usar ropa/uniformes/disfraces sexualizados, o que de otra manera crean un ambiente sexualizado.
           Si un participante incurre en un comportamiento abusivo, los organizadores de la conferencia pueden tomar cualquier acción que estimen oportuna, incluyendo advertencias al ofensor o su expulsión de la conferencia sin reembolso.
           Si estás sufriendo algún abuso, adviertes abusos sobre otra persona, o tienes alguna otra preocupación, por favor contacta con algún miembro del personal de la conferencia inmediatamente. El personal de la conferencia puede ser fácilmente identificado, ya que vestirán camisetas del evento.
           El personal de la conferencia estará contento de ayudar a los participates a contactar con la seguridad del hotel/sala o con las autoridades locales, proveer escolta o asistir de otra manera a aquellos que estén sufriendo abusos para que se sientan seguros mientras dure la conferencia. Valoramos tu asistencia.
           Esperamos que los participantes sigan estas reglas en la la conferencia, talleres y eventos sociales relacionados con la conferencia.
           
  cocCredits: >
              Fuente original y créditos: <a href="http://2012.jsconf.us/#/about">http://2012.jsconf.us/#/about</a> &amp; <a href="http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy">The Ada Initiative</a><br>
              Por favor, ayuda traduciendo o mejorando: <a href="https://github.com/leftlogic/confcodeofconduct.com">http://github.com/leftlogic/confcodeofconduct.com</a><br>
              Este trabajo está licenciado bajo <a rel="license" href="http://creativecommons.org/licenses/by/3.0/deed.en_US">Creative Commons Atribución 3.0 Unported License</a>
               
email: "info@codemotion.es"
baseurl: ""
url: "codemotion.es"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""

# Head
twitterAccount: "@codemotion_es"

# Main Block
mainImage: "codemotion.jpg"
mainButtons:
  - link: "https://www.koliseo.com/codemotion/codemotion-madrid/r4p/5685252034920448"
    i18n: "SendYourTalk"


# Location Block
universityName: "Universidad San Pablo CEU"
streetAddress: "Campus de Montepríncipe"
addressLocality: "Boadilla del monte, Madrid"
placeCoordinates: "40.399567, -3.837917,17"
mapCenterCoordinates: "40.399567, -3.839917,17"
mobileCenterMapCoordinates: "40.399567, -3.837917"